source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target 'DemoViperWithAPI' do
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'ObjectMapper', '3.4.1'
    pod 'SwiftyJSON', '~> 4.2.0'

    pod 'SVProgressHUD',                        :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
    pod 'SDWebImage'


    #Keyboard manager
    pod 'IQKeyboardManagerSwift', '6.1.1'
    pod 'ReachabilitySwift'

    #Alert controller
    pod 'SDCAlertView' , '9.0.1'
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == 'ReachabilitySwift'
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '4.2'
                end
            end
        end
    end
end
