source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target 'DemoViper' do
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'ObjectMapper', '3.4.1'
    pod 'SwiftyJSON', '~> 4.2.0'

    pod 'SVProgressHUD',                        :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
    pod 'SDWebImage'
end
